eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8070
spring:
  application:
    name: dean
  config:
    import: optional:configserver:http://localhost:8888

application:
  config:
    exam-url: http://localhost:8022/api/v1/exams
